/**
 * Terms of Service for Frontier Intelligence LLC / Morpheus Inference API
 * Last updated: February 25, 2026
 */

export const TERMS_OF_SERVICE_CONTENT = `# **TERMS OF SERVICE**

**Last updated: February 25, 2026**

---

## **Agreement to Our Legal Terms**

These Terms of Service ("Legal Terms" or "Terms") constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you"), and **Frontier Intelligence LLC** ("Company," "we," "us," or "our"), concerning your access to and use of the Morpheus Inference API and any related products and services that refer or link to these Legal Terms (collectively, the "Services").

You can contact us by email at **frontierintelligence@proton.me**.

You agree that by accessing the Services, you have read, understood, and agreed to be bound by all of these Legal Terms. **IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.**

Supplemental terms and conditions or documents that may be posted on the Services from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Legal Terms at any time and for any reason by updating the "Last updated" date above. It is your responsibility to periodically review these Legal Terms to stay informed of updates. Your continued use of the Services after the posting of revised Legal Terms means you accept and agree to the changes.

---

## **Table of Contents**

1. Our Services
2. Intellectual Property Rights
3. User Representations
4. Credits, Payments, and Billing
5. API Access and Usage
6. Prohibited Activities
7. User Content (Input and Output)
8. Contribution License
9. Third-Party Model Terms
10. Data Practices
11. Services Management
12. Term and Termination
13. Modifications and Interruptions
14. Governing Law
15. Dispute Resolution (Arbitration)
16. Corrections
17. Disclaimer
18. Limitations of Liability
19. Indemnification
20. Force Majeure
21. Electronic Communications, Transactions, and Signatures
22. Miscellaneous
23. Contact Us

---

## **1. Our Services**

The Morpheus Inference API is an API service that provides a pass-through interface to the Morpheus Decentralized Inference Marketplace. The Services allow users to purchase credits and consume them to access AI text generation and embedding capabilities provided by third-party inference providers on the decentralized marketplace.

The Services are not intended for distribution to, or use by, any person or entity in any jurisdiction where such distribution or use would be contrary to law or regulation or would subject us to any registration requirement within such jurisdiction. Those who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws.

### **1.1 AI Transparency and Disclosure**

**AI SYSTEM NOTICE.** You acknowledge and agree that the Services route your requests to AI models operated by third-party inference providers on the Morpheus Decentralized Inference Marketplace. Content you receive from the Services is AI-generated by these third-party models.

**YOUR RESPONSIBILITY FOR OUTPUT.** You are responsible for how you use any output generated through the Services ("Output"), including ensuring that your use complies with applicable laws, third-party rights, and any applicable model licenses.

**DISCLOSURE WHEN REQUIRED.** If you use Output to communicate with others (including customers, users, or the public), you agree to make any disclosures required by applicable law or platform rules indicating that content is AI-generated or AI-assisted, where required.

### **1.2 Nature of the Service**

You acknowledge that:

* Frontier Intelligence LLC operates as an API frontend layer and does not host, operate, or control the underlying AI models.
* The AI models available through the Services are provided by third-party inference providers on the Morpheus Decentralized Inference Marketplace.
* Model availability, performance, and behavior may vary and are subject to change without notice.
* We do not guarantee the availability of any specific model at any time.

---

## **2. Intellectual Property Rights**

### **2.1 Our Intellectual Property**

We are the owner or licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs, text, and graphics in the Services (collectively, the "Content"), as well as the trademarks, service marks, and logos contained therein (the "Marks"). The Content and Marks are protected by applicable intellectual property laws and treaties.

### **2.2 Your Use of Our Services**

Subject to your compliance with these Legal Terms, we grant you a non-exclusive, non-transferable, revocable license to access and use the Services for your internal business purposes, personal use, or commercial purposes (including building products and services on top of the API and reselling API access to your own end users), subject to these Legal Terms.

Except as expressly permitted, no part of the Services and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited without our express prior written permission.

---

## **3. User Representations**

By using the Services, you represent and warrant that:

1. You have the legal capacity and you agree to comply with these Legal Terms.
2. You are at least 18 years old.
3. You will not use the Services for any illegal or unauthorized purpose.
4. Your use of the Services will not violate any applicable law or regulation.
5. You will comply with all applicable third-party model licenses and terms when using Output generated through the Services.

If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services.

---

## **4. Credits, Payments, and Billing**

### **4.1 Credit System**

The Services operate on a prepaid credit system. You must purchase credits before using the API. Credits are consumed based on your API usage (e.g., tokens processed, models used).

### **4.2 Credit Expiration**

All purchased credits expire one (1) year from the date of purchase. Expired credits are forfeited and non-refundable.

### **4.3 Pricing**

Current credit pricing is available on the Services. We reserve the right to change credit pricing at any time. Price changes will not affect credits that have already been purchased.

### **4.4 Payment Methods**

We accept payments in USD through Stripe and in USDC through Coinbase Commerce. All payment processing is handled by these third-party processors, and your use of their services is subject to their respective terms and privacy policies.

### **4.5 Refund Policy**

All credit purchases are final and non-refundable, except in the following circumstances:

* **Billing errors:** If you are charged incorrectly due to a system or processing error, we will refund the erroneous amount.
* **Accidental duplicate charges:** If you are charged more than once for the same purchase, we will refund the duplicate charge(s).

To request a refund for billing errors or duplicate charges, please contact us at frontierintelligence@proton.me with details of the transaction. Refunds will be processed to the original payment method.

### **4.6 Credits Upon Termination**

If your account is terminated due to a breach of these Legal Terms, all remaining credits in your account are immediately forfeited without refund. See Section 12 (Term and Termination) for details.

---

## **5. API Access and Usage**

### **5.1 API Keys**

Upon registering an account, you may generate API keys to access the Services. You are solely responsible for maintaining the confidentiality and security of your API keys. You must:

* Keep your API keys secure and confidential.
* Not share your API keys with unauthorized parties.
* Immediately notify us if you believe your API keys have been compromised.

You are responsible for all activity that occurs using your API keys, whether or not authorized by you. We reserve the right to revoke or disable API keys at any time if we suspect unauthorized use, abuse, or a security breach.

### **5.2 Rate Limits**

API rate limits and usage quotas are documented at apidocs.mor.org. We reserve the right to modify rate limits at any time to ensure fair usage and service stability.

### **5.3 Programmatic Access**

The Services are designed for programmatic access. Automated and programmatic use of the API is permitted and expected, provided such use complies with these Legal Terms, applicable rate limits, and does not constitute abuse of the Services.

### **5.4 Commercial Use and Reselling**

You are permitted to build commercial products and services on top of the Morpheus Inference API and to resell API access to your own end users, provided that:

* You comply with all provisions of these Legal Terms.
* You comply with all applicable third-party model licenses and terms (see Section 9).
* You are solely responsible for your relationship with your end users, including any terms of service, support, and obligations you provide to them.
* You agree to indemnify us for any claims arising from your end users' use of the Services through your products or services.

---

## **6. Prohibited Activities**

You may not access or use the Services for any purpose other than that for which we make the Services available. As a user of the Services, you agree not to:

* Use the Services to generate, store, or distribute child sexual abuse material (CSAM) or any content that sexually exploits minors.
* Use the Services to generate malware, ransomware, viruses, exploit code, or any software designed to damage, disrupt, or gain unauthorized access to computer systems or networks.
* Use the Services to generate content intended to facilitate terrorism, incite violence, or cause serious physical harm to any person.
* Use the Services to generate content that violates applicable law in your jurisdiction, including but not limited to content that constitutes harassment, threats, defamation, fraud, or identity theft.
* Use the Services to impersonate any person or entity or misrepresent your identity or affiliation for the purpose of deception, fraud, or violation of applicable law.
* Use the Services to generate or distribute content intended to manipulate, defraud, or mislead others in connection with a commercial transaction or an election.
* Attempt to circumvent, disable, or otherwise interfere with security-related features of the Services, including rate limits, authentication mechanisms, or access controls.
* Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Services, the servers on which the Services are hosted, or any server, computer, or database connected to the Services.
* Use the Services to conduct or facilitate distributed denial-of-service (DDoS) attacks or similar abuse against the Services or any third party.
* Trick, defraud, or mislead us, especially in any attempt to learn sensitive account information or gain unauthorized access.
* Use any information obtained from the Services to harass, abuse, or harm another person.
* Make improper use of our support services or submit false reports of abuse or misconduct.
* Collect usernames, email addresses, or other information about other users by electronic or other means for the purpose of sending unsolicited communications.
* Use the Services in any manner that could disable, overburden, damage, or impair the Services or interfere with any other party's use of the Services.

**Violation of these prohibited activities may result in immediate termination of your account and forfeiture of all remaining credits without refund.**

---

## **7. User Content (Input and Output)**

### **7.1 Definitions**

* **"Input"** means any content, data, prompts, instructions, files, or other material you submit to the Services through the API.
* **"Output"** means any content generated by the Services (via third-party inference providers) in response to your Input.

### **7.2 Responsibility for Input**

You are solely responsible for your Input and for all activity that occurs under your account. You represent and warrant that:

* You own your Input or have the necessary rights, licenses, consents, and permissions to submit it and to allow the processing described in these Legal Terms.
* Your Input does not infringe or violate any third-party rights (including copyright, trademark, privacy, publicity, confidentiality, or trade secret rights).
* You will not submit copyrighted material unless you have the right to do so (e.g., you own it, it is licensed to you, it is in the public domain, or your use is otherwise lawful).

### **7.3 Confidential Information**

You agree not to submit confidential information or trade secrets unless you have the legal right to do so and you accept the risk that processing involves routing through third-party inference providers on the Morpheus Decentralized Inference Marketplace (as described in our Privacy Policy). If you submit confidential information, you represent you are authorized to submit it and to permit its processing for the purpose of providing the Services.

### **7.4 Ownership of Output**

You own all rights in the Output generated through your use of the Services, subject to:

* These Legal Terms.
* Any applicable third-party model licenses, terms, or restrictions that apply to the specific AI model(s) used to generate the Output (see Section 9).
* Any third-party rights that may apply to underlying source materials.

It is your responsibility to understand and comply with any license terms or restrictions associated with the models you use.

---

## **8. Contribution License**

### **8.1 License to Operate the Services**

You retain ownership of your Input, but you grant us a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to host, store, reproduce, process, transmit, display, and (solely as necessary for formatting and technical delivery) modify your Input for the sole purpose of providing, maintaining, securing, and operating the Services, including routing your requests to inference providers, preventing abuse, complying with legal obligations, and enforcing these Legal Terms.

### **8.2 No Training on Your Data**

**We do not use your Input or Output to train, fine-tune, improve, or develop any AI models.** This is a contractual commitment. Your Input exists only in transit during request processing and is not logged or stored by us.

### **8.3 Feedback**

By sending us suggestions, ideas, or feedback, you agree we can use and share such feedback for any purpose without compensation to you.

---

## **9. Third-Party Model Terms**

### **9.1 Model Licenses Apply**

The AI models available through the Morpheus Inference API are provided by third-party inference providers and may be subject to their own licenses, terms of use, and acceptable use policies (collectively, "Model Terms"). By using a specific model through the Services, you agree to comply with all applicable Model Terms for that model.

### **9.2 Your Responsibility**

It is your sole responsibility to:

* Identify and review the applicable Model Terms for any model you access through the Services.
* Ensure that your use of the model and any Output generated by it complies with the applicable Model Terms.
* Ensure that any downstream use, distribution, or commercialization of Output complies with the applicable Model Terms.

### **9.3 No Warranty of Model Compliance**

We do not warrant or represent that use of any model through the Services complies with that model's license terms in every context. We do not provide legal advice regarding model licensing. You are solely responsible for your compliance.

---

## **10. Data Practices**

### **10.1 No Logging of Content**

We do not log, store, or retain the content of your API prompts (Input) or responses (Output). This data exists only in transit during the processing of your request and is not persisted on our servers.

### **10.2 Usage Metrics**

We collect aggregate usage metrics for billing and service optimization purposes, including tokens consumed, model used, timestamps, latency, error codes, and credit consumption. These metrics do not include the content of your prompts or responses.

### **10.3 Privacy**

Our collection and use of personal data is described in our Privacy Policy, which is incorporated by reference into these Legal Terms.

### **10.4 Third-Party Inference Providers**

You acknowledge that your Input is routed through the Morpheus Decentralized Inference Marketplace to third-party inference providers. While we do not pass any personal information to these providers and all requests are submitted through a single reference account, we cannot guarantee with absolute certainty that third-party inference providers do not log or store data that passes through their systems. We do not control the data practices of these decentralized providers.

---

## **11. Services Management**

We reserve the right, but not the obligation, to:

1. Monitor the Services for violations of these Legal Terms.
2. Take appropriate legal action against anyone who, in our sole discretion, violates the law or these Legal Terms, including suspending or terminating accounts and forfeiting remaining credits.
3. Refuse, restrict access to, limit the availability of, or disable the Services for any user.
4. Otherwise manage the Services to protect our rights and property and to facilitate the proper functioning of the Services.

---

## **12. Term and Termination**

These Legal Terms remain in full force and effect while you use the Services.

### **12.1 Termination by Us**

We may suspend or terminate your access to the Services, without prior notice or liability, for any reason or no reason, including if we believe you have violated these Legal Terms.

### **12.2 Termination for Breach**

If your account is terminated due to a breach of these Legal Terms:

* All remaining credits in your account are immediately forfeited without refund.
* You may not register and create a new account under your name or a false name.

### **12.3 Termination by You**

You may terminate your account at any time through your account settings at app.mor.org or by contacting us at frontierintelligence@proton.me. Upon voluntary termination, any remaining credits are forfeited. No refunds will be issued for unused credits.

### **12.4 Effect of Termination**

Upon termination, the following sections of these Legal Terms survive: Intellectual Property Rights, Disclaimer, Limitations of Liability, Indemnification, Governing Law, Dispute Resolution, and any other provisions that by their nature should survive termination.

---

## **13. Modifications and Interruptions**

We reserve the right to change, modify, or remove the contents of the Services at any time for any reason at our sole discretion without notice. We have no obligation to update any information on our Services.

**The Services are provided on an "as-available" basis.** We cannot guarantee the Services will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Services, resulting in interruptions, delays, or errors. You agree we have no liability for any loss, damage, or inconvenience caused by your inability to access or use the Services during any downtime or discontinuance of the Services.

Nothing in these Legal Terms will be construed to obligate us to maintain and support the Services or to supply any corrections, updates, or releases in connection therewith.

---

## **14. Governing Law**

These Legal Terms shall be governed by and defined following the laws of the **State of Wyoming**, without regard to conflict of law principles.

---

## **15. Dispute Resolution (Arbitration)**

### **15.1 Informal Negotiations**

To expedite resolution and control the cost of any dispute, controversy, or claim related to these Legal Terms (each a "Dispute"), you and we agree to first attempt to negotiate any Dispute informally for at least thirty (30) days before initiating arbitration. Informal negotiations begin upon written notice from one party to the other.

### **15.2 Binding Arbitration**

If the parties are unable to resolve a Dispute through informal negotiations, the Dispute shall be finally and exclusively resolved by binding arbitration.

* **Arbitrator:** A mutually agreed-upon arbitrator. If the parties cannot agree on an arbitrator within fifteen (15) days of a demand for arbitration, either party may petition a court of competent jurisdiction in the State of Wyoming to appoint an arbitrator.
* **Seat / Location:** Wyoming, or another location mutually agreed upon by the parties.
* **Language:** English.
* **Governing Law:** Wyoming law (to the extent not preempted by applicable federal law).

### **15.3 Class Action Waiver**

To the fullest extent permitted by law, you and we agree that arbitration will be conducted only on an individual basis and not in a class, consolidated, or representative action.

### **15.4 Exceptions**

Nothing in this section prevents either party from seeking injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of intellectual property rights or confidentiality obligations.

---

## **16. Corrections**

There may be information on the Services that contains typographical errors, inaccuracies, or omissions. We reserve the right to correct any errors and to change or update the information on the Services at any time, without prior notice.

---

## **17. Disclaimer**

**THE SERVICES ARE PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS. YOU AGREE THAT YOUR USE OF THE SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.**

### **17.1 Not Professional Advice**

**THE SERVICES AND OUTPUT ARE PROVIDED FOR GENERAL INFORMATIONAL PURPOSES ONLY AND DO NOT CONSTITUTE LEGAL, MEDICAL, FINANCIAL, OR OTHER PROFESSIONAL ADVICE. WE DO NOT CREATE A PROFESSIONAL-CLIENT RELATIONSHIP. YOU SHOULD SEEK INDEPENDENT PROFESSIONAL ADVICE WHEN APPROPRIATE.**

### **17.2 No Guarantee of Accuracy, Completeness, or Fitness**

**WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY, COMPLETENESS, RELIABILITY, TIMELINESS, OR FITNESS OF ANY OUTPUT OR ANY INFORMATION GENERATED THROUGH THE SERVICES. OUTPUT MAY BE INCORRECT, INCOMPLETE, MISLEADING, BIASED, OR OUTDATED. YOU ARE SOLELY RESPONSIBLE FOR EVALUATING AND INDEPENDENTLY VERIFYING ALL OUTPUT BEFORE RELYING ON IT.**

### **17.3 Third-Party Inference Providers**

**THE AI MODELS ACCESSED THROUGH THE SERVICES ARE OPERATED BY THIRD-PARTY INFERENCE PROVIDERS ON THE MORPHEUS DECENTRALIZED INFERENCE MARKETPLACE. WE DO NOT CONTROL THESE MODELS OR PROVIDERS AND MAKE NO WARRANTIES REGARDING THEIR AVAILABILITY, PERFORMANCE, ACCURACY, SAFETY, OR COMPLIANCE WITH ANY LAW OR STANDARD.**

---

## **18. Limitations of Liability**

**TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL WE OR OUR DIRECTORS, MEMBERS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM OR RELATED TO YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.**

**IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF OR RELATED TO THESE LEGAL TERMS OR THE SERVICES EXCEED THE GREATER OF (A) THE AMOUNT PAID BY YOU TO US DURING THE SIX (6) MONTHS PRIOR TO THE EVENT GIVING RISE TO THE CLAIM OR (B) ONE HUNDRED DOLLARS ($100).**

Some jurisdictions do not allow limitations of implied warranties or exclusion/limitation of certain damages; in such cases, some or all of the above may not apply to you.

---

## **19. Indemnification**

You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all respective officers, members, agents, partners, and employees, from and against any loss, damage, liability, claim, demand, or expense (including reasonable attorneys' fees) arising out of or related to:

1. Your Input or your use of Output.
2. Your use of the Services, including any products or services you build on top of the API.
3. Your end users' use of the Services through your products or services.
4. Your breach of these Legal Terms.
5. Your violation of any law or the rights of a third party.
6. Your violation of any applicable third-party model license or terms.

---

## **20. Force Majeure**

We shall not be liable for any failure or delay in the performance of our obligations under these Legal Terms where such failure or delay results from circumstances beyond our reasonable control, including but not limited to: natural disasters, acts of God, fire, flood, earthquake, pandemic, epidemic, war, terrorism, civil unrest, government actions or orders, labor disputes, power outages, internet or telecommunications failures, cyberattacks, failures of third-party service providers (including infrastructure providers and inference providers on the Morpheus Decentralized Inference Marketplace), or any other event outside our reasonable control.

During such events, our obligations under these Legal Terms will be suspended for the duration of the force majeure event. Credit expiration timelines will not be extended due to force majeure events.

---

## **21. Electronic Communications, Transactions, and Signatures**

Visiting the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide electronically satisfy any legal requirement that such communication be in writing.

**YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES.**

---

## **22. Miscellaneous**

These Legal Terms and any policies posted by us constitute the entire agreement between you and us regarding the Services. Our failure to enforce any right or provision shall not operate as a waiver of such right or provision.

If any provision of these Legal Terms is determined to be unlawful, void, or unenforceable, that provision is severable and does not affect the validity and enforceability of the remaining provisions.

We may assign any or all of our rights and obligations under these Legal Terms to others at any time. You may not assign or transfer your rights or obligations under these Legal Terms without our prior written consent.

There is no joint venture, partnership, employment, or agency relationship created between you and us as a result of these Legal Terms or use of the Services.

A person who is not a party to these Legal Terms shall have no right to enforce any term of these Legal Terms.

---

## **23. Contact Us**

To resolve a complaint regarding the Services or to receive further information, please contact us at:

**Frontier Intelligence LLC**
Wyoming, United States
Email: **frontierintelligence@proton.me**
`;
